### ISSUE TITLE
tointeger output different from the actual value

### ISSUE THREAD

**Issue by taimazB** [NCAR/ncl#124]
Hi;

Using ncl ver. 6.4.0:

ncl 0> a = 1580298522.
ncl 1> print(tointeger(a))
(0)     1580298496

Why the difference!?

**Comment by khallock** [comment]
Hi @85TT58,

While this behavior may seem incorrect, it is actually the expected result in NCL due to the fact that floating point data types have a limited amount of precision available to represent numbers. Try printing `a` in decimal notation using the following code and you can see that this actually occurs in the representation of the variable `a` and _not_ as part of the conversion to an integer:
```
ncl 0> a = 1580298522.
ncl 1> print(sprintf("%f", a))
(0)     1580298496.000000
ncl 2> print(tointeger(a))
(0)     1580298496
```

Specifically, the variable `a` above is a **single precision 32-bit floating point** value: https://en.wikipedia.org/wiki/Single-precision_floating-point_format

That Wikipedia page has a section describing the [precision limits on integer values](https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Precision_limits_on_integer_values), which indicates that for a value between 2<sup>30</sup> + 1 and 2<sup>31</sup>, the floating point representation will be rounded to the nearest multiple of 256, which ends up being 1580298496 in this case.

The following code with `b` as an integer type variable (instead of a floating point type variable) gives us a familiar answer:
```
ncl 3> b = 1580298522    
ncl 4> print((b / 256) * 256)
(0)     1580298496
```

I hope this helps clarify why you're seeing that difference in your code!

**Comment by pilotchute** [comment]
Solved, closing.
