### ISSUE TITLE
ncl=6.6.2 does not allow hdf5=1.10.6 

### ISSUE THREAD

**Issue by valeriupredoi** [NCAR/ncl#133]
hey guys, `hdf5=1.10.5` is getting pretty old by now and we'd really appreciate installing the newest version `1.10.6` - problem is we also need `ncl` in our environment and `6.6.2` (any hash) will not allow for hdf5=1.10.6`: `- hdf5 >=1.10.5,<1.10.6.0a0` - any chance you could relax this restriction soon, if possible, please? Cheers muchly :beer:

**Comment by pilotchute** [comment]
I'll look into it. We've just had some staff turnover, so it may be a little while until we have time to test NCL against hdf5 1.10.6.

I'll update once I've collected some info.

**Comment by valeriupredoi** [comment]
great, cheers muchly! Take your time and good luck with the new staff :beer:

**Comment by Dave-Allured** [comment]
FYI Macports is successfully building NCARG/NCL 6.6.2 with HDF5 1.10.6 since 2020 January 6.  I have used this build on Mac OS with good results.
https://ports.macports.org/port/ncarg/summary

**Comment by valeriupredoi** [comment]
cool, but we (our software package) must support primarily Linux and OSX within a conda environment; conda will refuse to install `hdf5=1.10.6` and `ncl=6.6.2` in one env because of conflicting package requirements :beer: 

@pilotchute you guys had a chance to look into this by any chance? Cheers muchly :beer:

**Comment by erogluorhan** [comment]
> cool, but we (our software package) must support primarily Linux and OSX within a conda environment; conda will refuse to install `hdf5=1.10.6` and `ncl=6.6.2` in one env because of conflicting package requirements 🍺
> 
> @pilotchute you guys had a chance to look into this by any chance? Cheers muchly 🍺

Hi Valeri,

Sorry that it has been a long while since your last question here. As @pilotchute pointed out earlier, we, the GeoCAT group, had to deal with staff turnover as well as other technical restructuring tasks for a while, so we could not prioritize our support activities. 

As a response to your question: I have had a chance to test **NCL=6.6.2** (build **h34292a7_23**) with **hdf5=1.10.6** (build **nompi_hc457bb4_1110**) in my MacOS conda environment without a problem, neither with the installation nor with the executions. SO, before diving deeper, could you please confirm if you had a chance to try the same builds in you environment? If yes and your issue continues, could you please give some details about your development environment?

Thanks!

**Comment by valeriupredoi** [comment]
hello @erogluorhan cheers much for the update, completely understand the circumstances :+1: Yes, I have just managed to build a conda env with `ncl=6.6.2` and `hdf5=1.10.6` so all is good and many thanks for you guys' work! I will now proceed to detect which other dependency impedes the upgrade to 1.10.6 in our full environment but as far as NCL is concerned, all's jolly good :beer:

**Comment by erogluorhan** [comment]
> hello @erogluorhan cheers much for the update, completely understand the circumstances 👍 Yes, I have just managed to build a conda env with `ncl=6.6.2` and `hdf5=1.10.6` so all is good and many thanks for you guys' work! I will now proceed to detect which other dependency impedes the upgrade to 1.10.6 in our full environment but as far as NCL is concerned, all's jolly good 🍺

Valeriu, that sounds great! Yes, please let us know if we can be of any help once you detect the dependency that led to the initial issue within your environment. I am thus closing the issue for now, but please feel free to reopen if it is ever needed. Cheers!

Orhan @ NCAR/GeoCAT

**Comment by valeriupredoi** [comment]
no worries mate, will do, stay safe, all :beer:
