### ISSUE TITLE
SPECX program question

### ISSUE THREAD

**Issue by mariajmolina** [NCAR/ncl#147]
Hello! Quick question -- Is there supposed to be a space between the function being called and the input arguments on the referenced line? Thanks for your help.

https://github.com/NCAR/ncl/blob/83ea393b25e15bd850c034c364edc25c0257702b/ni/src/lib/nfpfort/specx_dp.f#L546

**Comment by Dave-Allured** [comment]
That space is optional, according to fortran standards.  In general, the standards allow any number of spaces between elements within a statement.

In practice this becomes a matter of style.  Some people program consistently with or without a space between the function name and the parenthesis.  Some people don't care and use the space inconsistently.  I try to use single space for functions and subroutines, and no space when subscripting variables, so that I can tell them apart.

**Comment by mariajmolina** [comment]
@Dave-Allured Thanks for clarifying this! Since asking, I continued looking thru scripts and have tested the space or no space, and have realized what you are saying. I like the approach of differentiating between functions/subroutines and scripting variables. I'll go ahead and close -- thanks again!
