### ISSUE TITLE
Disappointment in switchover

### ISSUE THREAD

**Issue by CathySmithNOAA** [NCAR/ncl#65]
I am disappointed in the switch to python and I think it will ultimately require a lot of time and effort on the part of the scientists to be able to do what they can already do now. There are a number of reasons. Some are possible to address in NCL/python and I suspect some are not.  

1) Python has version and compatibility issues among the various libraries that are needed. I can honestly say I have never had a clean installation of complicated set of python code for a project.
2) Python will take time to learn for users who do not use it now. More specifically, scientists, who do NOT need to be software engineers will need to learn program in python, install packages,  run it, debug it, understand the error messages, and find examples. Python is not as easy to use as NCL, MATLAB, etc. and scientists should be spending their time on science and not software. Especially as there is no real advantage I have heard about for using python. You can run system commands in NCL now after all. 
3) Python current plotting and analysis are not great. The mapping programs are limited. Code is not geared specifically to the meteorological or oceanographic communities. Having NCL routines be python will help but only if they work seemlessly together with the same paradigms for the different packages. 
4) **Documentation is the key.** I couldn't do anything if I couldn't look up an example of how to do it and what the parameters mean. This could be done but will require much work. If the public  analysis or mapping packages change (which NCL has no control over) this might be problematic. 
5). I have 100K lines of NCL code myself now (used for my own work and for web applications). In our lab alone, I would guess there is 1M lines of NCL code. Why switch if there is no advantage?
6) There is this idea out there that scientists can simply publish their juypter notebooks of python code and all will be well and code will be public. This idea is bad for many reasons (buggy code, misunderstood code, bad code, too-long-to-explain code, version changes, etc). This isn't a reason not to switch NCL but people should know where some of the push for python is coming from. 
7) This decision seems to be driven from the top (managers) and maybe students: not from scientists. I have not seen anyone on the NCL or other lists clamoring for python. Python is used and has some functionality not in NCL but that functionality is necessarily really needed by many scientists. And much of it can be addressed by combining scripting languages with NCL code. I tend to use Perl and NCL together, for example.  In one talk I saw at AGU, a women had converted all her group's code to python from MATLAB. Of all the people in the group only 2 used her new python library. She didn't understand why they didn't (nor did she ask them).

**Comment by Try2Code** [comment]
> I am disappointed in the switch to python and I think it will ultimately require a lot of time and effort on the part of the scientists to be able to do what they can already do now. There are a number of reasons. Some are possible to address in NCL/python and I suspect some are not.
> 
>     1. Python has version and compatibility issues among the various libraries that are needed. I can honestly say I have never had a clean installation of complicated set of python code for a project.
> 

True IMO. Any future NCL-python version should be 3.x compatible or to both 2.7 and 3.x (which is not such a big task). Relying on many external libraries can be a pain for users. And finding the best way between internal and external functionality will be hard to the NCL developers. But if they support conda and share their environment(s), this should be solvable.

>     2. Python will take time to learn for users who do not use it now. More specifically, scientists, who do NOT need to be software engineers will need to learn program in python, install packages,  run it, debug it, understand the error messages, and find examples. Python is not as easy to use as NCL, MATLAB, etc. and scientists should be spending their time on science and not software. Especially as there is no real advantage I have heard about for using python. You can run system commands in NCL now after all.

Just like any language Python has some concepts and caveats one has to learn. This defo applies to NCL, too. It's concepts of 'resource', how to define a plot, the lack of a module/namespace concept, high-level data structure and built-in parallelism ... I missed a lot when I started with NCL. Python has such a big standard library for all kinds of stuff.
Scientist should do science and not programming? To me this does not sound reasonable, because almost everything is done through programs. Weather prediction and climate science are simple impossible without programming. I wish scientist would focus a little more on being a programmer because they get they results for their papers by these programs.   I saw to many bad code from scientists, who refused to work on it.

> 
>     3. Python current plotting and analysis are not great. The mapping programs are limited. Code is not geared specifically to the meteorological or oceanographic communities. Having NCL routines be python will help but only if they work seemlessly together with the same paradigms for the different packages.

this will be a key feature, I agree. But I am sure, the NCL developers are aware of this. 

> 
>     4. **Documentation is the key.** I couldn't do anything if I couldn't look up an example of how to do it and what the parameters mean. This could be done but will require much work. If the public  analysis or mapping packages change (which NCL has no control over) this might be problematic.

That's why NCL has to stick to certain release versions of such libraries. That's a common issue with software. But you can use these libs instead of programming everything yourself. 
The online documentation of NCL is just great - one of the best I've ever seen. 

>        5). I have 100K lines of NCL code myself now (used for my own work and for web applications). In our lab alone, I would guess there is 1M lines of NCL code. Why switch if there is no advantage?
> 

you don't have to switch AFAIK. NCL releases will be available for quite some time. As long as you don't need new features, there should be problem.

>     5. There is this idea out there that scientists can simply publish their juypter notebooks of python code and all will be well and code will be public. This idea is bad for many reasons (buggy code, misunderstood code, bad code, too-long-to-explain code, version changes, etc). This isn't a reason not to switch NCL but people should know where some of the push for python is coming from.

yes, around Jupyter  there is quite some hype I don't understand 

> 
>     6. This decision seems to be driven from the top (managers) and maybe students: not from scientists. I have not seen anyone on the NCL or other lists clamoring for python. Python is used and has some functionality not in NCL but that functionality is necessarily really needed by many scientists. And much of it can be addressed by combining scripting languages with NCL code. I tend to use Perl and NCL together, for example.  In one talk I saw at AGU, a women had converted all her group's code to python from MATLAB. Of all the people in the group only 2 used her new python library. She didn't understand why they didn't (nor did she ask them).

If you can then spent the license money formerly gone to Matlab to your students, this might make sense. I had a hard time to use NCL with any other language, e.g. I wanted to use CDO. this was only possible through 'system()'. Writing complex scripts that can create different plots for different kinds if input files was quite challenging. It needed 2000 lines of code and from my point of view it should have worked with 600 less. Most NCL scripts I saw are designed for a single plot driven through an additional bash script, which passes parameters to the NCL code via the environment.  writing two scripts instead of one is really bad IMO. But the handling of command line arguments in NCL need so many quotes that it becomes unusable.

I personally stopped using NCL because of these limitations although its one of the few programs to plot the native grid of the model I use (ICON). I am really looking forward to a plotting library that is as good as NCL and flexible and fast like python.

**Comment by erogluorhan** [comment]
Hi @CathySmithNOAA @Try2Code 

Thank you very much for sharing your thoughts with us! Community feedback is always a lot of help for us on determining / revising our project goals and roadmaps. I am sorry to hear your disappointments though. 

I'd like to provide a longer response to try answering significant points one by one; however, I'd first like to direct you to our [November 2020 Community Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update), if you haven't had look at it yet. I believe that this update letter might contain answers to some of the points in this issue; however, please let me know if I can give further answers to any of the points.

Orhan at GeoCAT
