### ISSUE TITLE
BUILD: sometimes .o files are built instead of libraries - is there a good reason?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ncl#7]
Sometimes in the build, libraries are built.

Other times, .o files are built, where a library would be expected. For example the ngmath library is compiled from ngmathbd.f to ngmathbd.o. Here's the yMakefile:

```
SUBDIRS = lib bin examples

OBJECTS = ngmathbd.o
FSOURCES = ngmathbd.f

RelocatableTarget(libngmathbd.o,$(OBJECTS))
```

Here's the Makefile.am in that directory:

```
# This is an automake file for NCL
# Ed Hartnett 9/5/18

SUBDIRS = lib bin examples

libngmathbd.o: ngmathbd.o
	ld -r -o $@ $^

ngmathbd.o: ngmathbd.f
	$(FC) -c ${FCFLAGS} -o $@ $^

# Install this "lib" file.
robjdir = $(prefix)/lib/ncarg/robj
robj_HEADERS = libngmathbd.o

EXTRA_DIST = ngmathbd.f

CLEANFILES = *.o
```

This would be a lot simpler if we just compiled ngmathbd into a library.

I also not that ngmathbd.o is seemingly never used anywhere else in the build. Is it needed?

But even if not, the question still applies, since there are other cases of this. So can I make these into proper libraries? It would be easier and more correct, and would work the same. But different files would end up being installed. Instead of libngmathbd.o we would have libngmathdb.a (for static only builds) and a bunch of additional files for shared library builds.

**Comment by marylhaley** [comment]
The libngmathbd.o is a set of dummy blockdata routines that was used to
handle potential blockdata initialization issues we had a long time ago.

Many years ago we ran into compilers that were not correctly initializing
blockdata routines, so we had to create a function to force call these
routines, which caused the blockdata variables to get properly initialized.

I'm guessing this file and the similar "libncargbd.o" one in the
ncarg2d/src/liboptional/ncarbd directory is no longer needed. I don't
recall why it was named "libxxx.o" instead of "xxxxx.o".

Any changes you make would also need to be reflected in the ncargf77.csh,
ncargcc.csh, and ncargf90.csh scripts in $NCARG/ncarg2d/src/bin/scripts, as
these are the scripts that are used to compile NCAR Graphics programs and
they reference these files.

Really, though, you could probably just remove them and any references to
them. When we refactor the source code, this will likely happen anyway
because we will be trying to get rid of unneeded files.

**Comment by edhartnett** [comment]
OK, great. I will take these .o files out of the autotools build. By removing the Makefile.am, and removing the SUBDIR in the parent directory's Makefile.am, the autotools build will just ignore this code. It will not be built, or packaged into distributions.

WRT scripts:

Right now I don't think the ncargcc.csh etc. scripts that I am generating will work. ;-) But I will clean them up after everything else is working. Basically the issue is that your build thinks of a bunch of libraries each (potentially) in different places. 

The autotools handles this by thinking of a list of libraries, and it's up to you to set the CPPFLAGS, LDFLAGS, etc., to ensure that all libraries (and include files) are found. The build does not attempt to keep track of where each is found.

The end result will be the same. The LDFLAGS and CPPFLAGS that the autotools build ends up using will be injected into those scripts so that they work. But this has not happened yet.
