### ISSUE TITLE
Conda environment issue when needing r-base and NCL

### ISSUE THREAD

**Issue by valeriupredoi** [NCAR/ncl#87]
Hi guys, we can no longer create a conda virtual environment in which __both__ `ncl` and `r-base` get installed (we had this environment solve and create until a week or so ago with ncl=conda-forge/6.5.0 and r-base=conda-forge/3.5.1). Here are the inter-dep settings that don't work:

 - ncl from conda-forge (either 6.5.0 or 6.6.2; we can not use ncl<6.5.0 due to project requirements);
 - r-base from either conda-forge or pkgs/main/linux-64 (NOTE that the env gets solved when using the r channel but the r-base version that gets installed is then 3.2.2 which is obsolete; we need 3.5.1 or 3.5.2 or newer for project purposes);
 
Here are some typical conda messages:
```
(pin r-base, let ncl free)
UnsatisfiableError: The following specifications were found to be in conflict:
  - ncl
  - r-base=3.5.2

(pin both ncl and r-base)
UnsatisfiableError: The following specifications were found to be in conflict:
  - ncl=6.5.0
  - r-base=3.5.2

(pin both ncl and r-base but for older versions for both)
UnsatisfiableError: The following specifications were found to be in conflict:
  - ncl=6.5.0
  - r-base=3.5.1
```

We've done a lot more investigations, you can see https://github.com/ESMValGroup/ESMValTool/pull/958 and https://github.com/ESMValGroup/ESMValTool/issues/918

Apologies for the issue creation for something that is not specifically only NCL-related but we would appreciate any insight from you if you are aware of such a problem and know how to fix it! Great many thanks in advance!!

**Comment by valeriupredoi** [comment]
Just as a side-note to this issue, I am not sure if you are aware that ncl=6.4.0 does not work anymore in a conda virtual env (Linux x64):
```
$ conda list ncl
# packages in environment at /home/valeriu/anaconda3/envs/esmvaltool_T6:
#
# Name                    Version                   Build  Channel
ncl                       6.4.0           blas_openblas_9  [blas_openblas]  conda-forge
$ ncl -V
ncl: error while loading shared libraries: libpoppler.so.71: cannot open shared object file: No such file or directory
```
trying to update poppler results in conda simply wanting to remove ncl:
```
$ conda install -c conda-forge poppler=0.71.0
...
The following packages will be REMOVED:

  ncl-6.4.0-blas_openblas_9
...
```

**Comment by khallock** [comment]
Hi @valeriupredoi, 

Thanks for sharing this issue!

I tried installing `ncl` and `r-base` in the same environment using several permutations of pinned versions and got the same UnsatisfiableError message that you reported, but only on Linux (the Mac packages are somehow compatible, even without specifying a version for either package).

I took a closer look at the available `r-base` packages on conda-forge (https://anaconda.org/conda-forge/r-base/files) and noticed that all of the files are at least several months old. In January 2019, conda-forge switched compilers from `gcc=4.8.5` provided by the "defaults" channel to their own `gcc_linux-64=7.3.0` package, creating incompatibilities between certain packages compiled with the old and new compilers, respectively.

Fortunately, conda-forge created the label `cf201901` as a sort of snapshot before switching over to their new `gcc_linux-64` compiler, and in my brief testing I was able to use the "channel" `conda-forge/label/cf201901` to create a working environment:
```
# this installs ncl=6.5.0=blas_openblash04324b8_3 and r-base=3.5.1=h391c2eb_5 on my system
conda create -c conda-forge/label/cf201901 -n ncl_r ncl r-base
```

Note that any other packages will also need to be installed using `-c conda-forge/label/cf201901` in order to avoid breaking the environment (or alternatively, you can include them in the original `conda create` command).

I'm not particularly familiar with the `r-base` package, but I think this incompatibility issue should be resolved with the next `r-base` package release. (See [conda-forge/r-base-feedstock](https://github.com/conda-forge/r-base-feedstock) for more info about the `r-base` package.)

Regarding installing `ncl=6.4.0`, I'm not sure how to address the `libpoppler` issue. As you observed, the `ncl` binary throws a shared library error because it's missing the correct version of `libpoppler` , but every attempt at installing `poppler=0.71.0` results in `ncl` being uninstalled. Building a "new" NCL 6.4.0 package using updated dependencies would probably solve the problem, but it would likely require some (unjustifiable) effort to maintain.

I hope this helps!

**Comment by valeriupredoi** [comment]
hey @khallock you are life saver, man! Cheers ever so much! I managed to create the env with all the needed deps (including bloody r-base) and run the tests and all, in a nutshell, it works! I have been trying to find a solution for this issue for the past two days and really didnt want to start `apt install`ing the R base :grin:

Don't worry about ncl=6.4.0, we don't need to use it anyway, I just wanted to prompt you to a problem that might be asked around and offer you a cause right way (poppler) but given that that ncl version is pretty old, I don't think people will ask about its functionality anymore.

BTW do you have an idea if the conda folk will retire that frozen mirror `cf201901` soon ie if they do without fixing `conda-forge` in advance, we'd be back in the bogs (and I guess a lot of others too).

Anyways, cheers again! :beer:

**Comment by valeriupredoi** [comment]
cheers again @khallock - we (ESMValTool devs) owe you a beer :beer:
